-- Generated by nwg-displays on 2026-08-05 at 16:37:13. Do not edit manually.

hl.monitor({
    output = "eDP-2",
    mode = "2560x1600@165.0",
    position = "4702x1228",
    scale = 1.6
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@59.95",
    position = "2142x1060",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "702x0",
    scale = 1.0,
    transform = 1
})
