-- Generated by nwg-displays on 2026-08-05 at 09:46:19. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-2",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-2"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-2"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-6",
    default = true
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-6"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-6"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DP-5",
    default = true
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DP-5"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "DP-5"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "eDP-2"
})
