-- Layouts, focus, cursor and the misc knobs.
hl.config({
  general = { layout = "dwindle", resize_on_border = true },
  dwindle = { preserve_split = true, special_scale_factor = 0.8 },
  master = { new_status = "master", new_on_top = true, mfact = 0.5 },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    vrr = 2,
    mouse_move_enables_dpms = true,
    enable_swallow = false,
    swallow_regex = "^(kitty)$",
    focus_on_activate = false,
    initial_workspace_tracking = 0,
    middle_click_paste = false,
    enable_anr_dialog = true,
    anr_missed_pings = 15,
    allow_session_lock_restore = true,
  },
  debug = { vfr = true },
  binds = {
    workspace_back_and_forth = true,
    allow_workspace_cycles = true,
    pass_mouse_when_bound = false,
  },
  xwayland = { enabled = true, force_zero_scaling = true },
  render = { direct_scanout = 0 },
  cursor = {
    sync_gsettings_theme = true,
    no_hardware_cursors = 1,
    enable_hyprcursor = true,
    warp_on_change_workspace = 2,
    no_warps = true,
  },
})
